"""initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-02-26 00:00:00.000000
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=True),
        sa.Column('role', sa.String(50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_table('term',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('is_archived', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('term_id', sa.String(36), nullable=False),
        sa.Column('teacher_id', sa.String(36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
        sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollment',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('course_id', sa.String(36), nullable=False),
        sa.Column('student_id', sa.String(36), nullable=False),
        sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('course_id', 'student_id')
    )
    op.create_table('assignment',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('course_id', sa.String(36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('type', sa.String(50), nullable=False),
        sa.Column('max_points', sa.Numeric(10, 2), nullable=False),
        sa.Column('due_date', sa.Date(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('assignment_id', sa.String(36), nullable=False),
        sa.Column('student_id', sa.String(36), nullable=False),
        sa.Column('earned_points', sa.Numeric(10, 2), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('assignment_id', 'student_id')
    )
    op.create_table('grading_config',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('display_mode', sa.String(50), nullable=False),
        sa.Column('effective_from_term_id', sa.String(36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['effective_from_term_id'], ['term.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_boundary',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('grading_config_id', sa.String(36), nullable=False),
        sa.Column('label', sa.String(length=10), nullable=False),
        sa.Column('min_percentage', sa.Numeric(5, 2), nullable=False),
        sa.Column('max_percentage', sa.Numeric(5, 2), nullable=False),
        sa.Column('gpa_value', sa.Numeric(3, 2), nullable=True),
        sa.ForeignKeyConstraint(['grading_config_id'], ['grading_config.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('grading_config_id', 'label')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade_boundary')
    op.drop_table('grading_config')
    op.drop_table('grade')
    op.drop_table('assignment')
    op.drop_table('enrollment')
    op.drop_table('course')
    op.drop_table('term')
    op.drop_table('user')
    # ### end Alembic commands ###
